services:

  php:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: devine4life
      MARIADB_DATABASE: first_in
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
